### ISSUE TITLE
is it work for xiaomi mijia smart cam

### ISSUE THREAD

**Issue by naut1co** [niclet/xiaomi_hack#7]
Hi,

is that work for the xiaomi mijia smart camera?

**Comment by niighthawk** [comment]
i want to know also ...

**Comment by niclet** [comment]
It has been developed for the Mijia 360 (rounded), not for the one which looks like a cube. So there are very little chance to work with it.

**Comment by bknill** [comment]
Hi, do you know if it's possible this will work with the cube shaped camera?   Or are you saying  you've tried and it doesn't work?

**Comment by niclet** [comment]
I just think, I don't have the smart camera. I can't buy all xiaomi devices ;)

**Comment by bknill** [comment]
ha right OK. I'll get one and have a go. Usually they have similar ways to control.. the Xiaomi Yi's all worked in a similar way.

**Comment by reggaemanu** [comment]
The cube shape camera (Xiaofang camera) already have a hack that works
fine.

**Comment by naut1co** [comment]
mijia smart cam is not the Cube (xiaofang) but an other which looks like the antz.

**Comment by bknill** [comment]
This is the one I want to get a telnet connection to  -  Xiaomi mijia 3.5K Panorama Action Camera 


https://www.gearbest.com/action-cameras/pp_621510.html?vip=2663089&gclid=Cj0KCQjwgIPOBRDnARIsAHA1X3T_3WLm5GOuQJYpzqeyraS4qxI79KH_UET1oNBfMaF_QGiVD-ioKPMaAsDzEALw_wcB

I want to be able to start it recording from my own app then access the video files.
